services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./src/:/var/www/html/src
      - ./client/:/var/www/html/client/
      - ./static/:/var/www/html/static/
